<?php 
/*------------------------------------------------------------------------
# APL Solutions and Vision Co., LTD
# ------------------------------------------------------------------------
# Copyright (C) 2008-2010 APL Solutions and Vision Co., LTD. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: APL Solutions and Vision Co., LTD
# Websites: http://www.joomlavision.com/ - http://www.magentheme.com/
-------------------------------------------------------------------------*/ 
?>
<?php if($this->getConfig('enabled')){?> <!-- start enable module -->
	<div class="block mt-fb-block">
		<?php if($this->getConfig('title')) {?>
			<div class="block-title">
				<strong><span><?php echo $this->__($this->getConfig('title'));?></span></strong>
			</div>
		<?php } ?>
		<?php $fb=$this->getDataFB();?>
		<?php echo $this->__($fb);?>
		<div style="display: none;"><a href="http://www.9magentothemes.com" title="Magento Themes">Magento Themes</a> and Magento Extensions by 9MagentoThemes.Com</div>
	</div>
<?php }//end enabled?>
